name: deploy

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build container image
        uses: redhat-actions/buildah-build@v2.5
        with:
          image: quay.io/redhatqe/openstack-gitlab-runner
          tags: ${{ env.RELEASE_VERSION }} latest
          dockerfiles: Containerfile
          oci: true
      - name: Push image to registry
        uses: redhat-actions/push-to-registry@v2.2
        with:
          image: openstack-gitlab-runner
          tags: ${{ env.RELEASE_VERSION }} latest
          registry: quay.io/redhatqe
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_TOKEN }}
